# Generated by Django 6.0.5 on 2026-07-18 04:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('pv', 'Photovoltaik'), ('fuel_cell', 'Brennstoffzelle'), ('diesel', 'Dieselgenerator'), ('chp', 'Blockheizkraftwerk'), ('wind', 'Windenergie')], max_length=20)),
                ('peak_power_kw', models.DecimalField(decimal_places=2, help_text='Gesamtleistung des Systems in kW/kWp', max_digits=10)),
                ('inverter_power_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Wechselrichterleistung', max_digits=10, null=True)),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Speicherkapazität', max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_systems', to='devices.home')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
