# Generated by Django 6.0.5 on 2026-07-18 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('module_count', models.PositiveIntegerField(default=0)),
                ('peak_power_kwp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('azimuth_deg', models.IntegerField(help_text='0=N, 90=O, 180=S, 270=W')),
                ('tilt_deg', models.IntegerField(default=35, help_text='Dachneigung')),
                ('shading_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='producer.generatorsystem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
