# Generated by Django 6.0.5 on 2026-07-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_generatorstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatorstring',
            name='azimuth_deg',
        ),
        migrations.AddField(
            model_name='generatorstring',
            name='orientation',
            field=models.CharField(choices=[('N', 'Nord'), ('NE', 'Nordost'), ('E', 'Ost'), ('SE', 'Südost'), ('S', 'Süd'), ('SW', 'Südwest'), ('W', 'West'), ('NW', 'Nordwest')], default='S', max_length=2),
        ),
    ]
