# Generated by Django 6.0.5 on 2026-07-19 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
        ('producer', '0003_remove_generatorstring_azimuth_deg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Generator Typ',
                'verbose_name_plural': 'Generator Typen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('azimuth_deg', models.IntegerField()),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ausrichtung',
                'verbose_name_plural': 'Ausrichtungen',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='generatorsystem',
            name='system_type',
        ),
        migrations.AddField(
            model_name='generatorsystem',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generator_system', to='devices.device'),
        ),
        migrations.AddField(
            model_name='generatorsystem',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generator_systems', to='producer.generatortype'),
        ),
        migrations.AlterField(
            model_name='generatorstring',
            name='orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strings', to='producer.orientation'),
        ),
    ]
