# Generated by Django 6.0.5 on 2026-07-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_generatortype_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorstring',
            name='orientation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strings', to='producer.orientation'),
        ),
        migrations.AlterField(
            model_name='generatorsystem',
            name='generator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator_systems', to='producer.generatortype'),
        ),
    ]
