# Generated by Django 6.0.5 on 2026-07-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_alter_generatorstring_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorsystem',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generator_systems', to='producer.generatortype'),
        ),
    ]
