# Generated by Django 6.0.5 on 2026-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_alter_generatorsystem_generator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatorsystem',
            name='peak_power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gesamtleistung des Systems in kW/kWp', max_digits=10, null=True),
        ),
    ]
