# Generated by Django 6.0.5 on 2026-07-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0007_alter_generatorsystem_peak_power_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatortype',
            name='icon',
            field=models.CharField(blank=True, default='⚡', max_length=20),
        ),
    ]
