# Generated by Django 6.0.5 on 2026-06-01 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metering', '0003_alter_balanceslot_meter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('account_holder', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='billing_ban_tenant__118ef5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_member__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_member__isnull', False)), _connector='OR'), name='bankaccount_owner_xor'), models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='bankaccount_user_requires_no_tenant'), models.CheckConstraint(condition=models.Q(('owner_member__isnull', True), ('tenant__isnull', False), _connector='OR'), name='bankaccount_member_requires_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(choices=[('supply', 'Supply'), ('sharing', 'Sharing'), ('dynamic', 'Dynamic pricing supply')], default='supply', max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_member__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_member__isnull', False)), _connector='OR'), name='contract_owner_xor'), models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='contract_user_requires_no_tenant'), models.CheckConstraint(condition=models.Q(('owner_member__isnull', True), ('tenant__isnull', False), _connector='OR'), name='contract_member_requires_tenant')],
            },
        ),
        migrations.CreateModel(
            name='UserBalanceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('consumption_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('generation_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('self_consumption_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('grid_import_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('grid_export_kwh', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balance_slots', to='metering.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'period_start'], name='billing_use_user_id_47cb45_idx'), models.Index(fields=['meter', 'period_start'], name='billing_use_meter_i_fd51fd_idx'), models.Index(fields=['tenant', 'period_start'], name='billing_use_tenant__d5878e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'meter', 'period_start'), name='uniq_user_meter_period')],
            },
        ),
        migrations.CreateModel(
            name='UserMeterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_assignments', to='metering.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='billing_use_user_id_9377ad_idx'), models.Index(fields=['meter', 'is_active'], name='billing_use_meter_i_c6c1fc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('meter',), name='uniq_active_assignment_per_meter')],
            },
        ),
    ]
