# Generated by Django 6.0.5 on 2026-06-07 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantmembership_tenant'),
        ('billing', '0003_remove_bankaccount_bankaccount_owner_xor_and_more'),
        ('core', '0003_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='bankaccount_user_requires_no_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='contract_user_requires_no_tenant',
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='bankaccount_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='contract_user_requires_no_tenant'),
        ),
    ]
