# Generated by Django 6.0.5 on 2026-06-07 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantmembership_tenant'),
        ('billing', '0004_remove_bankaccount_bankaccount_user_requires_no_tenant_and_more'),
        ('core', '0003_alter_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='bankaccount_member_requires_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='contract_member_requires_tenant',
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='bankaccount_membership_requires_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='contract_membership_requires_tenant'),
        ),
    ]
