# Generated by Django 6.0.5 on 2026-06-20 00:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('home', 'identifier')},
        ),
        migrations.RemoveField(
            model_name='devicemetric',
            name='energy_kwh',
        ),
        migrations.RemoveField(
            model_name='devicemetric',
            name='power_w',
        ),
        migrations.AddField(
            model_name='device',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='devicemetric',
            name='metric',
            field=models.CharField(default='unknown', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemetric',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='devicemetric',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.home'),
        ),
        migrations.AlterField(
            model_name='home',
            name='mqtt_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['device', 'timestamp'], name='devices_dev_device__c419e7_idx'),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicerole'),
        ),
        migrations.AddField(
            model_name='floor',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='devices.home'),
        ),
        migrations.AlterField(
            model_name='device',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.floor'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='devices.floor'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.room'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['home', 'identifier'], name='devices_dev_home_id_64c6e5_idx'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='home_label',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
