# Generated by Django 6.0.5 on 2026-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicerole_floor_room_alter_device_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
