# Generated by Django 6.0.5 on 2026-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_home_mqtt_password_home_mqtt_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mqtt_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
