# Generated by Django 6.0.5 on 2026-06-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_home_mqtt_provisioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSelectedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='devices_dev_home_id_64c6e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemetric',
            name='devices_dev_device__c419e7_idx',
        ),
        migrations.RenameField(
            model_name='devicemetric',
            old_name='metric',
            new_name='metric_key',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='home',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mqtt_password',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mqtt_provisioned',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mqtt_token',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mqtt_username',
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.room'),
        ),
        migrations.AlterField(
            model_name='devicemetric',
            name='unit',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='deviceselectedmetric',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_metrics', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_types', to='devices.devicerole'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='devicetypemetric',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_metrics', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='devicetypemetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.metricdefinition'),
        ),
        migrations.AddField(
            model_name='deviceselectedmetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.metricdefinition'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='device',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_seen',
        ),
        migrations.AlterUniqueTogether(
            name='devicetypemetric',
            unique_together={('device_type', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='deviceselectedmetric',
            unique_together={('device', 'metric')},
        ),
    ]
