# Generated by Django 6.0.5 on 2026-06-23 23:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_deviceselectedmetric_devicetype_devicetypemetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='mqtt_provisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='mqtt_token',
            field= models.UUIDField(
                        null=True,
                        blank=True,
                        unique=False,
                        editable=False
                    )

        ),
        migrations.AddField(
            model_name='home',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('home', 'identifier')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['home', 'identifier'], name='devices_dev_home_id_64c6e5_idx'),
        ),
    ]
