# Generated by Django 6.0.5 on 2026-06-23 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_home_created_at_home_mqtt_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='mqtt_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
