# Generated by Django 6.0.5 on 2026-06-23 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_home_mqtt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='mqtt_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
