# Generated by Django 6.0.5 on 2026-06-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_first_seen_device_floor_device_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='role',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.RemoveField(
            model_name='devicetypemetric',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicetypemetric',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='device',
            name='configured',
        ),
        migrations.RemoveField(
            model_name='device',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='role',
        ),
        migrations.RemoveField(
            model_name='device',
            name='room',
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('measurement_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devices.device')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.floor')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.home')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicerole')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.room')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceSelectedMetric',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='DeviceTypeMetric',
        ),
    ]
