# Generated by Django 6.0.5 on 2026-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_remove_devicetype_role_remove_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='home',
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
