# Generated by Django 6.0.5 on 2026-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_remove_floor_home_remove_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='configured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
