# Generated by Django 6.0.5 on 2026-06-26 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_device_configured'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetric1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'bucket'], name='devices_dev_device__b24390_idx')],
                'unique_together': {('device', 'bucket')},
            },
        ),
        migrations.CreateModel(
            name='DeviceMetric5m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'bucket'], name='devices_dev_device__677c12_idx')],
                'unique_together': {('device', 'bucket')},
            },
        ),
    ]
