# Generated by Django 6.0.5 on 2026-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_devicemetric1m_devicemetric5m'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='delete_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='pending_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
