# Generated by Django 6.0.5 on 2026-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_device_active_device_delete_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='energy_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='energy_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
