# Generated by Django 6.0.5 on 2026-07-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_deviceconfig_energy_group_deviceconfig_energy_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
