# Generated by Django 6.0.5 on 2026-07-03 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_energygroup_energysource'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='energy_group_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.energygroup'),
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='energy_source_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.energysource'),
        ),
    ]
