# Generated by Django 6.0.5 on 2026-07-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_deviceconfig_energy_group_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfig',
            name='energy_group_ref',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='energy_source_ref',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='energy_group',
        ),
        migrations.RemoveField(
            model_name='deviceconfig',
            name='energy_source',
        ),
        migrations.DeleteModel(
            name='EnergyGroup',
        ),
        migrations.DeleteModel(
            name='EnergySource',
        ),
    ]
