# Generated by Django 6.0.5 on 2026-07-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_remove_deviceconfig_energy_group_ref_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['device', 'metric_key', '-timestamp'], name='metric_latest_idx'),
        ),
    ]
