# Generated by Django 6.0.5 on 2026-07-06 18:58

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_devicemetric_metric_latest_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mqtt_profile',
            field=models.CharField(choices=[('iobroker', 'ioBroker'), ('shelly', 'Shelly'), ('generic', 'Generic')], default='generic', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='mqtt_token',
            field=models.CharField(default=devices.models.generate_mqtt_token, editable=False, max_length=16, unique=True),
        ),
    ]
