# Generated by Django 6.0.5 on 2026-07-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_device_mqtt_profile_alter_home_mqtt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mqtt_profile',
        ),
    ]
