# Generated by Django 6.0.5 on 2026-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_remove_device_mqtt_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mqtt_profile',
            field=models.CharField(default='generic', max_length=20),
        ),
    ]
