# Generated by Django 6.0.5 on 2026-07-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_mqttprofile_home_mqtt_profile_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='mqtt_profile_ref',
        ),
        migrations.AlterField(
            model_name='device',
            name='mqtt_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.mqttprofile'),
        ),
    ]
