# Generated by Django 6.0.5 on 2026-07-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_remove_home_mqtt_profile_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetric15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.IntegerField()),
                ('energy_wh', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMetric1h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('bucket', models.DateTimeField(db_index=True)),
                ('avg', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('count', models.IntegerField()),
                ('energy_wh', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='devicemetric1m',
            name='devices_dev_device__b24390_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicemetric5m',
            name='devices_dev_device__677c12_idx',
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric1m',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric5m',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devicemetric1m',
            name='energy_wh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemetric1m',
            name='metric_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='devicemetric5m',
            name='energy_wh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemetric5m',
            name='metric_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric1m',
            unique_together={('device', 'metric_key', 'bucket')},
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric5m',
            unique_together={('device', 'metric_key', 'bucket')},
        ),
        migrations.AddIndex(
            model_name='devicemetric1m',
            index=models.Index(fields=['device', 'metric_key', 'bucket'], name='devices_dev_device__f5f223_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric1m',
            index=models.Index(fields=['bucket', 'metric_key'], name='devices_dev_bucket_5f6a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric5m',
            index=models.Index(fields=['device', 'metric_key', 'bucket'], name='devices_dev_device__da864c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric5m',
            index=models.Index(fields=['bucket', 'metric_key'], name='devices_dev_bucket_161058_idx'),
        ),
        migrations.AddField(
            model_name='devicemetric15m',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicemetric1h',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='devicemetric15m',
            index=models.Index(fields=['device', 'metric_key', 'bucket'], name='devices_dev_device__c10039_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric15m',
            index=models.Index(fields=['bucket', 'metric_key'], name='devices_dev_bucket_df6b0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric15m',
            unique_together={('device', 'metric_key', 'bucket')},
        ),
        migrations.AddIndex(
            model_name='devicemetric1h',
            index=models.Index(fields=['device', 'metric_key', 'bucket'], name='devices_dev_device__c15907_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemetric1h',
            index=models.Index(fields=['bucket', 'metric_key'], name='devices_dev_bucket_3d393b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric1h',
            unique_together={('device', 'metric_key', 'bucket')},
        ),
    ]
