# Generated by Django 6.0.5 on 2026-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_devicemetric15m_devicemetric1h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
