# Generated by Django 6.0.5 on 2026-07-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
        ('producer', '0008_generatortype_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfig',
            name='measurement_type',
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='generator_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producer.generatortype'),
        ),
    ]
