# Generated by Django 6.0.5 on 2026-07-22 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_remove_deviceconfig_measurement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='metric_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.metricdefinition'),
        ),
    ]
