# Generated by Django 6.0.5 on 2026-07-31 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_home_city_home_latitude_home_longitude_and_more'),
        ('energy', '0004_emssignalsource_unique_home_device_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='energy_signal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.emssignaltype'),
        ),
    ]
