# Generated by Django 6.0.5 on 2026-08-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_alter_deviceconfig_energy_signal_type'),
        ('energy', '0004_emssignalsource_unique_home_device_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='energy_signal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='energy.emssignaltype'),
        ),
    ]
