# Generated by Django 6.0.5 on 2026-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_deviceresource'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['device', '-timestamp'], name='dm_device_timestamp_idx'),
        ),
    ]
