# Generated by Django 6.0.5 on 2026-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_devicemetric_dm_device_timestamp_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLatestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(db_index=True, max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=16)),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['timestamp', 'device', 'metric_key'], name='dm_ts_dev_key_idx'),
        ),
        migrations.AddField(
            model_name='devicelatestmetric',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_metrics', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='devicelatestmetric',
            index=models.Index(fields=['device', 'metric_key'], name='dev_latest_metric_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicelatestmetric',
            constraint=models.UniqueConstraint(fields=('device', 'metric_key'), name='unique_device_latest_metric'),
        ),
    ]
