# Generated by Django 6.0.5 on 2026-06-10 22:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meter_type', models.CharField(choices=[('electricity', 'Electricity'), ('pv', 'PV'), ('battery', 'Battery')], default='electricity', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('integration_type', models.CharField(choices=[('tibber', 'Tibber'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=32)),
                ('tibber_home_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_tibber_sync', models.DateTimeField(blank=True, null=True)),
                ('owner_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='accounts.tenantmembership')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_meters', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts_start', models.DateTimeField()),
                ('ts_end', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('obis_code', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('source', models.CharField(default='system', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('ingestion_delay_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'core_intervalreading',
            },
        ),
        migrations.CreateModel(
            name='BalanceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('generation_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('self_consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_import_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_export_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'core_balanceslot',
            },
        ),
        migrations.CreateModel(
            name='AggregatedReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'core_aggregatedreading',
            },
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant', 'serial_number'], name='core_meter_tenant__2242dd_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant'], name='core_meter_tenant__e42577_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['integration_type'], name='core_meter_integra_95d312_idx'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_membership__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_membership__isnull', False)), _connector='OR'), name='meter_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='meter_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='meter_membership_requires_tenant'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['tenant', 'ts_start'], name='core_interv_tenant__061f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['meter', 'ts_start'], name='core_interv_meter_i_5f7225_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['tenant', 'obis_code', 'ts_start'], name='core_interv_tenant__4a8449_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intervalreading',
            unique_together={('meter', 'ts_start', 'obis_code')},
        ),
        migrations.AlterUniqueTogether(
            name='balanceslot',
            unique_together={('meter', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['meter', 'period_start'], name='core_aggreg_meter_i_9ae3b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedreading',
            unique_together={('meter', 'period_start')},
        ),
    ]
