# Generated by Django 6.0.5 on 2026-06-11 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberEnergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_role', models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('prosumer', 'Prosumer')], default='consumer', max_length=20)),
                ('grid_connection_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profile', to='accounts.tenantmembership')),
            ],
            options={
                'db_table': 'core_memberenergyprofile',
            },
        ),
        migrations.CreateModel(
            name='MeterRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='core.meter')),
            ],
            options={
                'db_table': 'core_meterregister',
                'unique_together': {('meter', 'obis_code')},
            },
        ),
    ]
