# Generated by Django 6.0.5 on 2026-06-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_slug_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
