# Generated by Django 6.0.5 on 2026-06-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_memberenergyprofile_meterregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedreading',
            name='unit',
            field=models.CharField(default='kWh', max_length=16),
        ),
    ]
