# Generated by Django 6.0.5 on 2026-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aggregatedreading_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='source',
            field=models.CharField(choices=[('imsys', 'iMSys'), ('mqtt', 'MQTT'), ('tibber', 'Tibber'), ('sungrow', 'Sungrow'), ('manual', 'Manual')], default='manual', max_length=32),
        ),
    ]
