#####################
# backend/settings.py
#####################
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

from celery.schedules import crontab
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-dev-key")
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

FRONTEND_URL = "http://localhost:5173"

HTTPS = os.getenv("HTTPS", "False") == "True"

SECURE_SSL_REDIRECT = HTTPS
SESSION_COOKIE_SECURE = HTTPS
CSRF_COOKIE_SECURE = HTTPS

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if HTTPS:
    SECURE_HSTS_SECONDS = 31536000  # 1 Jahr
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = "mail.sharegy.cloud"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False   # ❗ wichtig

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER ")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = "Sharegy <invite@sharegy.cloud>"

WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",  # ✅ hinzufügen
    "rest_framework_simplejwt",
    "corsheaders",
    "core",
    "integrations",  # ✅ DAS IST WICHTIG
    "tenants",
    "content",
    "design",
    "channels",
    "forecast",
    "accounts",
    "billing",
    "market",
    "energy",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

DATABASES["default"]["CONN_MAX_AGE"] = 60

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

USE_I18N = True
LANGUAGE_CODE = "de-DE"
LANGUAGES = [("de", "Deutsch"), ("en", "English")]
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/var/www/eswes/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = "/var/www/eswes/media/"

# Celery-Settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or os.getenv("REDIS_URL")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = "%(message)s"

CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270

CELERY_BEAT_SCHEDULE = {
    # Balance regelmäßig nachziehen
    "compute-balance": {
        "task": "billing.tasks.compute_balance_last_24h",
        "schedule": 300.0,
    },

    "allocate-user-balance": {
        "task": "billing.tasks.allocate_user_balance_last_24h",
        "schedule": 60.0,
    },

    # ✅ DB Aggregation triggern
    "rollup-15min": {
        "task": "core.tasks.rollup_15min",
        "schedule": 60.0,
    },

    # ✅ Balance berechnen (dirty slots)
    "process-dirty-balance": {
        "task": "core.tasks.process_dirty_balance",
        "schedule": 60.0,
    },

    # ✅ Tibber Daten holen
    "tibber-sync": {
        "task": "integrations.tasks.sync_tibber",
        "schedule": 1800.0,
    },

    # ✅ Strompreise (separat ok)
    "fetch-spot-prices-daily": {
        "task": "market.tasks.fetch_spot_prices_retry",
        "schedule": crontab(hour=13, minute=1),
    },
}


# REDIS

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("CHANNEL_LAYERS_URL")],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),
    }
}

# backend/settings.py (unten ergänzen)

#  DRF Auth
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}


# Defenition of Logging
DJANGO_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "context": {
            "()": "core.logging_filters.ContextFilter",
        }
    },
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(tenant_id)s %(event_id)s",
        },
        "console": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s [req=%(request_id)s tenant=%(tenant_id)s event=%(event_id)s]"
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "level": DJANGO_LOG_LEVEL,
            "formatter": "json" if not DEBUG else "console",
            "filters": ["context"],
        },
    },
    "root": {
        "handlers": ["stdout"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {"level": "INFO", "handlers": ["stdout"], "propagate": False},
            },
        "core": {   # ✅ WICHTIG
            "level": DJANGO_LOG_LEVEL,
            "handlers": ["stdout"],
            "propagate": False,
        },
        "integrations": {
            "level": DJANGO_LOG_LEVEL,
            "handlers": ["stdout"],
            "propagate": False,
        },

#        "django.db.backends": {
#            "handlers": ["stdout"],
#            "level": "DEBUG",
#        },

}



##################
# MQTT- Config
##################
MQTT_HOST = os.getenv("MQTT_HOST", "127.0.0.1")
MQTT_PORT = int(os.getenv("MQTT_PORT", "1883"))
MQTT_USERNAME = os.getenv("MQTT_USERNAME", "")
MQTT_PASSWORD = os.getenv("MQTT_PASSWORD", "")
MQTT_TLS = os.getenv("MQTT_TLS", "False") == "True"

MQTT_TOPIC = os.getenv("MQTT_TOPIC", "energy/+/+/telemetry")
MQTT_QOS = int(os.getenv("MQTT_QOS", "1"))

# Steady-State: Auto-Provision optional (in Prod eher False)
MQTT_AUTO_PROVISION = os.getenv("MQTT_AUTO_PROVISION", "False") == "True"

# MQTT Flags
MQTT_INGEST_ENABLED = os.getenv("MQTT_INGEST_ENABLED", "False") == "True"
MQTT_CLIENT_ID = os.getenv("MQTT_CLIENT_ID", "eswes-mqtt")
MQTT_PROFILE = os.getenv("MQTT_PROFILE", "default")

##################
# tibber token
##################
TIBBER_DEFAULT_TOKEN = os.getenv("TIBBER_TOKEN")
TIBBER_HOME_ID = os.getenv("TIBBER_HOME_ID")


##################
# Weather Fallback
##################
DEFAULT_WEATHER_LAT = 50.9
DEFAULT_WEATHER_LON = 6.9

##################
# Interval Abrechnung
##################
BILLING_SLOT_MINUTES = 15

##################
# CORS App
##################
#CORS_ALLOWED_ORIGINS = [FRONTEND_URL]

CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

if not DEBUG:
    CORS_ALLOWED_ORIGINS = [FRONTEND_URL]

CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]


##################
# Sentry Config
##################

SENTRY_DSN = os.getenv("SENTRY_DSN", "")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        send_default_pii=False,
        traces_sample_rate=0.1,
    )
