#####################
# backend/settings.py
#####################
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
##SECRET_KEY = "9kaut)zx)0#o7sb2a2nndi&l_6i&%ffa1a11#q+d3qxju*=a1m"
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"


ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

HTTPS = os.getenv("HTTPS", "False") == "True"

SECURE_SSL_REDIRECT = HTTPS
SESSION_COOKIE_SECURE = HTTPS
CSRF_COOKIE_SECURE = HTTPS

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if HTTPS:
    SECURE_HSTS_SECONDS = 31536000  # 1 Jahr
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0

WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",  # ✅ hinzufügen
    "rest_framework_simplejwt",
    "core",
    "integrations",  # ✅ DAS IST WICHTIG
    "metering",
    "channels",
    "forecast",
    "accounts",
    "billing",
    "market",
    "energy",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.RequestIdMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

USE_I18N = True
LANGUAGE_CODE = "de-DE"
LANGUAGES = [("de", "Deutsch"), ("en", "English")]
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "/var/www/eswes/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = "/var/www/eswes/media/"

# Celery-Settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL") or os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND") or os.getenv("REDIS_URL")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = "%(message)s"

CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270

CELERY_BEAT_SCHEDULE = {
    "aggregate-hourly": {
        "task": "metering.tasks.aggregate_hourly",
        "schedule": 3600.0,  # jede Stunde
    },
    "aggregate-daily": {
        "task": "metering.tasks.aggregate_daily",
        "schedule": 86400.0,
    },
    "aggregate-weekly": {
        "task": "metering.tasks.aggregate_weekly",
        "schedule": 604800.0,
    },
    "aggregate-monthly": {
        "task": "metering.tasks.aggregate_monthly",
        "schedule": 2592000.0,
    },
    "aggregate-yearly": {
        "task": "metering.tasks.aggregate_yearly",
        "schedule": 31536000.0,
    },
}

CELERY_BEAT_SCHEDULE.update(
    {
        # 15min Aggregation häufig laufen lassen, damit Late Data schnell korrigiert wird
        "aggregate-15min-every-5min": {
            "task": "metering.tasks.aggregate_15min",
            "schedule": 300.0,  # alle 5 Minuten
        },
        # Balance regelmäßig nachziehen
        "compute-balance-every-5min": {
            "task": "billing.tasks.compute_balance_last_2h",
            "schedule": 300.0,
        },
        # Optionale rollups
        "aggregate-hourly": {
            "task": "metering.tasks.aggregate_hourly",
            "schedule": 3600.0,
        },
        "aggregate-daily": {
            "task": "metering.tasks.aggregate_daily",
            "schedule": 86400.0,
        },
        "fetch-spot-prices": {
            "task": "market.tasks.fetch_spot_prices",
            "schedule": 3600.0,  # jede Stunde
        },
    }
)


# REDIS

import os

ASGI_APPLICATION = "backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("CHANNEL_LAYERS_URL")],
        },
    },
}


# backend/settings.py (unten ergänzen)

#  DRF Auth
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}


# Defenition of Logging
DJANGO_LOG_LEVEL = "DEBUG" if DEBUG else "INFO"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "context": {
            "()": "core.logging_filters.ContextFilter",
        }
    },
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(tenant_id)s %(event_id)s",
        },
        "console": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s [req=%(request_id)s tenant=%(tenant_id)s event=%(event_id)s]"
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "level": DJANGO_LOG_LEVEL,
            "formatter": "json" if not DEBUG else "console",
            "filters": ["context"],
        },
    },
    "root": {
        "handlers": ["stdout"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django": {"level": "INFO", "handlers": ["stdout"], "propagate": False},
        "integrations": {
            "level": DJANGO_LOG_LEVEL,
            "handlers": ["stdout"],
            "propagate": False,
        },
        "metering": {
            "level": DJANGO_LOG_LEVEL,
            "handlers": ["stdout"],
            "propagate": False,
        },
    },
}


##################
# MQTT- Config
##################
MQTT_HOST = os.getenv("MQTT_HOST", "127.0.0.1")
MQTT_PORT = int(os.getenv("MQTT_PORT", "1883"))
MQTT_USERNAME = os.getenv("MQTT_USERNAME", "")
MQTT_PASSWORD = os.getenv("MQTT_PASSWORD", "")
MQTT_TLS = os.getenv("MQTT_TLS", "False") == "True"

MQTT_TOPIC = os.getenv("MQTT_TOPIC", "energy/+/+/telemetry")
MQTT_QOS = int(os.getenv("MQTT_QOS", "1"))

# Steady-State: Auto-Provision optional (in Prod eher False)
MQTT_AUTO_PROVISION = os.getenv("MQTT_AUTO_PROVISION", "False") == "True"

# MQTT Flags
MQTT_INGEST_ENABLED = os.getenv("MQTT_INGEST_ENABLED", "False") == "True"
MQTT_CLIENT_ID = os.getenv("MQTT_CLIENT_ID", "eswes-mqtt")
MQTT_PROFILE = os.getenv("MQTT_PROFILE", "default")

##################
# tibber token
##################
TIBBER_DEFAULT_TOKEN = os.getenv("TIBBER_TOKEN")
TIBBER_HOME_ID = os.getenv("TIBBER_HOME_ID")


##################
# Weather Fallback
##################
DEFAULT_WEATHER_LAT = 50.9
DEFAULT_WEATHER_LON = 6.9

##################
# Interval Abrechnung
##################
BILLING_SLOT_MINUTES = 15

##################
# Sentry Config
##################

SENTRY_DSN = os.getenv("SENTRY_DSN", "")

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        send_default_pii=False,
        traces_sample_rate=0.1,
    )
