# Generated by Django 6.0.5 on 2026-06-01 01:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEnergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_role', models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('prosumer', 'Prosumer')], default='consumer', max_length=20)),
                ('grid_connection_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profile', to='metering.member')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meter_type', models.CharField(default='electricity', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts_start', models.DateTimeField()),
                ('ts_end', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('obis_code', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('source', models.CharField(default='MQTT', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('ingestion_delay_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('generation_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('self_consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_import_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_export_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'db_table': 'metering_balanceslot',
            },
        ),
        migrations.CreateModel(
            name='AggregatedReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MeterRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='metering.meter')),
            ],
            options={
                'indexes': [models.Index(fields=['meter', 'obis_code'], name='metering_me_meter_i_1684ac_idx')],
                'unique_together': {('meter', 'obis_code')},
            },
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant', 'serial_number'], name='metering_me_tenant__22c58f_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant'], name='metering_me_tenant__3ad827_idx'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_member__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_member__isnull', False)), _connector='OR'), name='meter_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='meter_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_member__isnull', True), ('tenant__isnull', False), _connector='OR'), name='meter_member_requires_tenant'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tenant'], name='metering_me_tenant__668cdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['tenant', 'ts_start'], name='metering_in_tenant__b76cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['meter', 'ts_start'], name='metering_in_meter_i_5b439d_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['tenant', 'obis_code', 'ts_start'], name='metering_in_tenant__539220_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intervalreading',
            unique_together={('meter', 'ts_start', 'obis_code')},
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['tenant', 'period_type', 'period_start'], name='metering_ag_tenant__4db058_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['meter', 'period_type', 'period_start'], name='metering_ag_meter_i_d8dce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedreading',
            unique_together={('meter', 'obis_code', 'period_start', 'period_type')},
        ),
    ]
