# Generated by Django 6.0.5 on 2026-05-27 01:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meter_type', models.CharField(default='electricity', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
        migrations.CreateModel(
            name='MeterRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='metering.meter')),
            ],
            options={
                'unique_together': {('meter', 'obis_code')},
            },
        ),
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts_start', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_late', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('ingestion_delay_seconds', models.IntegerField(blank=True, null=True)),
                ('ts_end', models.DateTimeField(blank=True, null=True)),
                ('obis_code', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='kWh', max_length=20)),
                ('source', models.CharField(default='WEBHOOK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ts_start'], name='metering_in_tenant__b76cb2_idx'), models.Index(fields=['meter', 'ts_start'], name='metering_in_meter_i_5b439d_idx')],
                'unique_together': {('meter', 'ts_start', 'obis_code')},
            },
        ),
        migrations.CreateModel(
            name='AggregatedReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('obis_code', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_type', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'unique_together': {('meter', 'obis_code', 'period_start', 'period_type')},
            },
        ),
    ]
