# Generated by Django 6.0.5 on 2026-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
