# Generated by Django 6.0.5 on 2026-05-30 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('generation_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('self_consumption_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_import_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('grid_export_kwh', models.DecimalField(decimal_places=3, max_digits=14)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'metering_balanceslot',
            },
        ),
        migrations.CreateModel(
            name='MemberEnergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_role', models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('prosumer', 'Prosumer')], default='consumer', max_length=20)),
                ('grid_connection_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'tenant')},
        ),
        migrations.RemoveField(
            model_name='meter',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='owner_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member'),
        ),
        migrations.AddField(
            model_name='meter',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aggregatedreading',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aggregatedreading',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.member'),
        ),
        migrations.AlterField(
            model_name='aggregatedreading',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
        migrations.AlterField(
            model_name='intervalreading',
            name='source',
            field=models.CharField(default='MQTT', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervalreading',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['tenant', 'period_type', 'period_start'], name='metering_ag_tenant__4db058_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['meter', 'period_type', 'period_start'], name='metering_ag_meter_i_d8dce0_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalreading',
            index=models.Index(fields=['tenant', 'obis_code', 'ts_start'], name='metering_in_tenant__539220_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['tenant'], name='metering_me_tenant__668cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant', 'serial_number'], name='metering_me_tenant__22c58f_idx'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant'], name='metering_me_tenant__3ad827_idx'),
        ),
        migrations.AddIndex(
            model_name='meterregister',
            index=models.Index(fields=['meter', 'obis_code'], name='metering_me_meter_i_1684ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_member__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_member__isnull', False)), _connector='OR'), name='meter_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='meter_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_member__isnull', True), ('tenant__isnull', False), _connector='OR'), name='meter_member_requires_tenant'),
        ),
        migrations.AddField(
            model_name='balanceslot',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.meter'),
        ),
        migrations.AddField(
            model_name='balanceslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
        migrations.AddField(
            model_name='memberenergyprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profile', to='metering.member'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
