# Generated by Django 6.0.5 on 2026-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_balanceslot_memberenergyprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
