# Generated by Django 6.0.5 on 2026-06-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_alter_balanceslot_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceslot',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metering.meter'),
        ),
    ]
