# Generated by Django 6.0.5 on 2026-06-02 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_alter_balanceslot_meter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='integration_type',
            field=models.CharField(choices=[('tibber', 'Tibber'), ('manual', 'Manual'), ('none', 'None')], default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_tibber_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='tibber_home_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['integration_type'], name='metering_me_integra_ff2aea_idx'),
        ),
    ]
