# Generated by Django 6.0.5 on 2026-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_tenant_latitude_tenant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
