# Generated by Django 6.0.5 on 2026-06-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metering", "0004_meter_integration_type_meter_last_tibber_sync_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(default="temp", unique=False),
            preserve_default=False,
        ),
    ]
