# Generated by Django 6.0.5 on 2026-06-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0005_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
