# Generated by Django 6.0.5 on 2026-06-07 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantmembership_tenant'),
        ('core', '0003_alter_tenant_slug'),
        ('metering', '0007_alter_aggregatedreading_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meter',
            name='meter_owner_xor',
        ),
        migrations.RemoveConstraint(
            model_name='meter',
            name='meter_user_requires_no_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='meter',
            name='meter_member_requires_tenant',
        ),
        migrations.RemoveField(
            model_name='aggregatedreading',
            name='member',
        ),
        migrations.AddField(
            model_name='aggregatedreading',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmembership'),
        ),
        migrations.AddField(
            model_name='meter',
            name='owner_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenantmembership'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_membership__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_membership__isnull', False)), _connector='OR'), name='meter_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', True), _connector='OR'), name='meter_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='meter_member_requires_tenant'),
        ),
        migrations.RemoveField(
            model_name='meter',
            name='owner_member',
        ),
    ]
