# Generated by Django 6.0.5 on 2026-06-07 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantmembership_tenant'),
        ('core', '0003_alter_tenant_slug'),
        ('metering', '0009_remove_meter_meter_user_requires_no_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meter',
            name='meter_member_requires_tenant',
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='meter_membership_requires_tenant'),
        ),
    ]
