# Generated by Django 6.0.5 on 2026-06-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='slug',
        ),
    ]
