# Generated by Django 6.0.5 on 2026-06-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_tenant_latitude_remove_tenant_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tenant',
            name='button_color',
            field=models.CharField(default='bg-orange-500', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='from-orange-400', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='to-orange-600', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='default', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
