# Generated by Django 6.0.5 on 2026-06-01 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('price_eur_per_kwh', models.DecimalField(decimal_places=6, max_digits=10)),
                ('source', models.CharField(default='energy-charts', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='market_spot_timesta_ae1867_idx')],
                'constraints': [models.UniqueConstraint(fields=('timestamp', 'source'), name='uniq_price_ts_source')],
            },
        ),
    ]
