# Generated by Django 6.0.5 on 2026-07-17 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPriceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(unique=True)),
                ('grid_fee_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('electricity_tax_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('concession_fee_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('kwk_levy_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('special_grid_levy_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('offshore_levy_ct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='HomeTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('tariff_type', models.CharField(choices=[('dynamic', 'Dynamic'), ('static', 'Static')], default='dynamic', max_length=20)),
                ('static_price_eur_per_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='devices.home')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
