# Generated by Django 6.0.5 on 2026-07-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
        ('market', '0002_electricitypriceconfig_hometariff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hometariff',
            constraint=models.UniqueConstraint(fields=('home', 'valid_from'), name='unique_home_tariff_date'),
        ),
    ]
