# Generated by Django 6.0.5 on 2026-07-27 00:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_hometariff_unique_home_tariff_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPriceDaySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('cheapest_hour', models.DateTimeField()),
                ('cheapest_hour_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('best_2h_start', models.DateTimeField()),
                ('best_2h_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('best_3h_start', models.DateTimeField()),
                ('best_3h_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('best_5h_start', models.DateTimeField()),
                ('best_5h_price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
