# Generated by Django 6.0.5 on 2026-06-13 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='remember',
            field=models.BooleanField(default=False),
        ),
    ]
