# Generated by Django 6.0.5 on 2026-06-07 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tenantmembership'),
        ('core', '0003_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantmembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant'),
        ),
    ]
