# Generated by Django 6.0.5 on 2026-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_magiclogintoken_expires_at_magiclogintoken_remember'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
