# Generated by Django 6.0.5 on 2026-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tenantmembership_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('profile', 'Profil'), ('meter', 'Meter'), ('energy', 'Energy'), ('billing', 'Billing'), ('done', 'Done')], default='welcome', max_length=20),
        ),
    ]
