# Generated by Django 6.0.5 on 2026-06-15 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_magiclogintoken_clicked_at_magiclogintoken_opened_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclogintoken',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magiclogintoken',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='magiclogintoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
