# Generated by Django 6.0.5 on 2026-06-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_eventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('setup', 'Setup'), ('done', 'Done')], default='welcome', max_length=20),
        ),
    ]
