# Generated by Django 6.0.5 on 2026-06-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usersettings_onboarding_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
