# Generated by Django 6.0.5 on 2026-07-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_eventlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclogintoken',
            name='remember',
        ),
    ]
