# Generated by Django 6.0.5 on 2026-05-25 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('api_key_hash', models.CharField(max_length=200, verbose_name='API key hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'API client',
                'verbose_name_plural': 'API clients',
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('event_type', models.CharField(default='METER_READING_BATCH', max_length=64, verbose_name='Event type')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Signature valid')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicate')], default='OK', max_length=16, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('api_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.apiclient', verbose_name='API client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_events', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Inbound webhook event',
                'verbose_name_plural': 'Inbound webhook events',
                'indexes': [models.Index(fields=['tenant', '-received_at'], name='idx_event_tenant_recv')],
            },
        ),
    ]
