# Generated by Django 6.0.5 on 2026-05-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundwebhookevent',
            options={},
        ),
        migrations.RenameIndex(
            model_name='inboundwebhookevent',
            new_name='integration_tenant__9b6d3c_idx',
            old_name='idx_event_tenant_recv',
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='event_type',
            field=models.CharField(default='METER_READING_BATCH', max_length=64),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='signature_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inboundwebhookevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('OK', 'OK'), ('ERROR', 'Error'), ('DUPLICATE', 'Duplicate')], default='RECEIVED', max_length=16),
        ),
        migrations.AddIndex(
            model_name='inboundwebhookevent',
            index=models.Index(fields=['status'], name='integration_status_cd8b32_idx'),
        ),
    ]
