# Generated by Django 6.0.5 on 2026-06-01 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('forecast_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source', models.CharField(default='forecast', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='forecast_tenant_ts_idx'), models.Index(fields=['tenant', 'source', 'timestamp'], name='forecast_tenant_source_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'timestamp', 'source'), name='unique_forecast_per_source')],
            },
        ),
        migrations.CreateModel(
            name='TenantWeatherSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('shortwave_radiation_wm2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ts'], name='weather_tenant_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ts'), name='unique_weather_snapshot_per_tenant_ts')],
            },
        ),
    ]
