# Generated by Django 6.0.5 on 2026-05-28 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('forecast_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source', models.CharField(default='forecast', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='forecast_so_tenant__3bb497_idx')],
                'unique_together': {('tenant', 'timestamp')},
            },
        ),
    ]
