# Generated by Django 6.0.5 on 2026-07-23 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('provider', models.CharField(max_length=50)),
                ('station_id', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('shortwave_radiation_wm2', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude', 'timestamp'], name='weather_obs_loc_ts_idx'), models.Index(fields=['provider', 'timestamp'], name='weather_obs_provider_ts_idx')],
            },
        ),
    ]
