# Generated by Django 6.0.5 on 2026-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('metering', '0002_balanceslot_memberenergyprofile_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solarforecast',
            name='forecast_so_tenant__3bb497_idx',
        ),
        migrations.AlterUniqueTogether(
            name='solarforecast',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='solarforecast',
            constraint=models.UniqueConstraint(fields=('tenant', 'timestamp', 'source'), name='unique_forecast_per_source'),
        ),
    ]
