# Generated by Django 6.0.5 on 2026-05-30 23:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_solarforecast_forecast_so_tenant__3bb497_idx_and_more'),
        ('metering', '0003_tenant_latitude_tenant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWeatherSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('shortwave_radiation_wm2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='metering.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'ts'], name='forecast_te_tenant__06879f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ts'), name='unique_weather_snapshot_per_tenant_ts')],
            },
        ),
    ]
