# Generated by Django 6.0.5 on 2026-06-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_solarforecast_tenant_and_more'),
        ('metering', '0006_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarforecast',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metering.tenant'),
        ),
    ]
