# Generated by Django 6.0.5 on 2026-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_weatherobservation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weatherobservation',
            constraint=models.UniqueConstraint(fields=('provider', 'station_id', 'timestamp'), name='weather_obs_unique_station_ts'),
        ),
    ]
