# Generated by Django 6.0.5 on 2026-06-07 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_slug'),
        ('forecast', '0003_alter_solarforecast_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarforecast',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
