# Generated by Django 6.0.5 on 2026-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_tenantweathersnapshot'),
        ('metering', '0003_tenant_latitude_tenant_longitude'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantweathersnapshot',
            new_name='weather_tenant_ts_idx',
            old_name='forecast_te_tenant__06879f_idx',
        ),
        migrations.AddIndex(
            model_name='solarforecast',
            index=models.Index(fields=['tenant', 'timestamp'], name='forecast_tenant_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='solarforecast',
            index=models.Index(fields=['tenant', 'source', 'timestamp'], name='forecast_tenant_source_ts_idx'),
        ),
    ]
