# Generated by Django 6.0.5 on 2026-07-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_home_city_home_latitude_home_longitude_and_more'),
        ('forecast', '0003_weatherobservation_weather_obs_unique_station_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherobservation',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_observations', to='devices.home'),
        ),
    ]
