# Generated by Django 6.0.5 on 2026-07-23 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_home_city_home_latitude_home_longitude_and_more'),
        ('forecast', '0004_weatherobservation_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('shortwave_radiation_wm2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='tenantweathersnapshot',
            name='weather_tenant_ts_idx',
        ),
        migrations.RemoveConstraint(
            model_name='tenantweathersnapshot',
            name='unique_weather_snapshot_per_tenant_ts',
        ),
        migrations.AddField(
            model_name='weatherforecast',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='devices.home'),
        ),
        migrations.RemoveField(
            model_name='tenantweathersnapshot',
            name='tenant',
        ),
        migrations.AddIndex(
            model_name='weatherforecast',
            index=models.Index(fields=['home', 'ts'], name='weather_home_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherforecast',
            constraint=models.UniqueConstraint(fields=('home', 'ts'), name='unique_weather_forecast_per_home_ts'),
        ),
        migrations.DeleteModel(
            name='TenantWeatherSnapshot',
        ),
    ]
