# Generated by Django 6.0.5 on 2026-07-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_weatherforecast_and_more'),
        ('producer', '0008_generatortype_icon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solarforecast',
            name='unique_forecast_per_source',
        ),
        migrations.RemoveIndex(
            model_name='solarforecast',
            name='forecast_tenant_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='solarforecast',
            name='forecast_tenant_source_ts_idx',
        ),
        migrations.AddField(
            model_name='solarforecast',
            name='generator_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_forecasts', to='producer.generatorstring'),
        ),
        migrations.AddIndex(
            model_name='solarforecast',
            index=models.Index(fields=['generator_string', 'timestamp'], name='forecast_string_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='solarforecast',
            index=models.Index(fields=['generator_string', 'source', 'timestamp'], name='forecast_string_source_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='solarforecast',
            constraint=models.UniqueConstraint(fields=('generator_string', 'timestamp', 'source'), name='unique_forecast_per_source'),
        ),
        migrations.RemoveField(
            model_name='solarforecast',
            name='tenant',
        ),
    ]
