# Generated by Django 6.0.5 on 2026-07-25 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_remove_solarforecast_unique_forecast_per_source_and_more'),
        ('producer', '0008_generatortype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('horizon_hours', models.PositiveIntegerField(default=24)),
                ('resolution_minutes', models.PositiveIntegerField(default=60)),
                ('model_version', models.CharField(blank=True, default='', max_length=50)),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='producer.generatorstring')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('forecast_kwh', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forecast.forecastrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['generator_string', 'generated_at'], name='forecast_run_string_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastvalue',
            index=models.Index(fields=['forecast_run', 'timestamp'], name='forecast_value_run_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastvalue',
            constraint=models.UniqueConstraint(fields=('forecast_run', 'timestamp'), name='forecast_value_run_ts_unique'),
        ),
    ]
