# Generated by Django 6.0.5 on 2026-07-27 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_forecastrun_forecastvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRunAccuracy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('mae_kwh', models.FloatField()),
                ('max_error_kwh', models.FloatField()),
                ('total_forecast_kwh', models.FloatField()),
                ('total_actual_kwh', models.FloatField()),
                ('delta_kwh', models.FloatField()),
                ('delta_percent', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('forecast_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy', to='forecast.forecastrun')),
            ],
        ),
    ]
