# Generated by Django 6.0.5 on 2026-07-14 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0028_alter_home_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDeviceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demo_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_targets', to='devices.device')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_sources', to='devices.device')),
            ],
            options={
                'unique_together': {('source_device', 'demo_device')},
            },
        ),
    ]
