# Generated by Django 6.0.5 on 2026-07-14 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
        ('devices', '0028_alter_home_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDeviceSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_until', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
