# Generated by Django 6.0.5 on 2026-06-18 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_remove_tenant_created_at_tenant_button_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('context', models.CharField(choices=[('global', 'Global'), ('tenant', 'Tenant')], db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['context', 'tenant', 'name', 'created_at'], name='tracking_ev_context_f1d652_idx'), models.Index(fields=['user', 'created_at'], name='tracking_ev_user_id_fec608_idx')],
            },
        ),
    ]
