# Generated by Django 6.0.5 on 2026-06-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('metering', '0006_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('image', 'Image'), ('cta', 'Call To Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantpage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='metering.tenant'),
        ),
    ]
