# Generated by Django 6.0.5 on 2026-06-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_tenantpage_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('text', 'Text'), ('image', 'Image'), ('cta', 'Call To Action'), ('sankey', 'Sankey')], max_length=50),
        ),
    ]
