# Generated by Django 6.0.5 on 2026-06-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_magiclogintoken_expires_at_magiclogintoken_remember'),
        ('core', '0003_aggregatedreading_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('pv', 'PV'), ('battery', 'Battery'), ('ev', 'EV'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('installed_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_assets', to='accounts.tenantmembership')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyAssetBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usable_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charge_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discharge_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='energy.energyasset')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyAssetEV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_charging_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ev', to='energy.energyasset')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyAssetPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_manufacturer', models.CharField(blank=True, max_length=100)),
                ('module_type', models.CharField(blank=True, max_length=100)),
                ('inverter_manufacturer', models.CharField(blank=True, max_length=100)),
                ('inverter_type', models.CharField(blank=True, max_length=100)),
                ('tilt_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('azimuth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_of_modules', models.IntegerField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='energy.energyasset')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='DE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_locations', to='accounts.tenantmembership')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_locations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='energyasset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.location'),
        ),
        migrations.CreateModel(
            name='SmartEnergySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('optimization_mode', models.CharField(choices=[('info', 'Information only'), ('auto', 'Automatic control'), ('hybrid', 'Hybrid')], default='info', max_length=20)),
                ('allow_direct_control', models.BooleanField(default=False)),
                ('optimize_ev', models.BooleanField(default=True)),
                ('optimize_battery', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_settings', to='accounts.tenantmembership')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_settings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('generation', 'Generation'), ('consumption', 'Consumption'), ('net', 'Net (grid)'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='core.meter')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_links', to='energy.energyasset')),
            ],
            options={
                'indexes': [models.Index(fields=['meter', 'relation_type'], name='energy_asse_meter_i_6312fe_idx')],
                'unique_together': {('asset', 'meter', 'relation_type')},
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'city'], name='energy_loca_tenant__bfd59e_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_membership__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_membership__isnull', False)), _connector='OR'), name='location_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='location_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='location_membership_requires_tenant'),
        ),
        migrations.AddIndex(
            model_name='energyasset',
            index=models.Index(fields=['tenant', 'asset_type'], name='energy_ener_tenant__b81348_idx'),
        ),
        migrations.AddIndex(
            model_name='energyasset',
            index=models.Index(fields=['owner_user', 'asset_type'], name='energy_ener_owner_u_a92304_idx'),
        ),
        migrations.AddIndex(
            model_name='energyasset',
            index=models.Index(fields=['owner_membership', 'asset_type'], name='energy_ener_owner_m_ad808e_idx'),
        ),
        migrations.AddConstraint(
            model_name='energyasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_membership__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_membership__isnull', False)), _connector='OR'), name='energyasset_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='energyasset',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='energyasset_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='energyasset',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='energyasset_membership_requires_tenant'),
        ),
        migrations.AddConstraint(
            model_name='smartenergysettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('owner_membership__isnull', True)), models.Q(('owner_user__isnull', True), ('owner_membership__isnull', False)), _connector='OR'), name='smartenergy_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='smartenergysettings',
            constraint=models.CheckConstraint(condition=models.Q(('owner_user__isnull', True), ('tenant__isnull', True), _connector='OR'), name='smartenergy_user_requires_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='smartenergysettings',
            constraint=models.CheckConstraint(condition=models.Q(('owner_membership__isnull', True), ('tenant__isnull', False), _connector='OR'), name='smartenergy_membership_requires_tenant'),
        ),
    ]
