# Generated by Django 6.0.5 on 2026-07-03 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_remove_deviceconfig_energy_group_ref_and_more'),
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSSignalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('pv', 'PV'), ('grid', 'Netz')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ems_signal_sources', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ems_signal_sources', to='devices.home')),
            ],
            options={
                'indexes': [models.Index(fields=['home', 'signal_type'], name='energy_emss_home_id_f6d0ab_idx')],
            },
        ),
    ]
