# Generated by Django 6.0.5 on 2026-07-31 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_emssignalsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSSignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='emssignalsource',
            new_name='energy_emss_home_id_b1fcb7_idx',
            old_name='energy_emss_home_id_f6d0ab_idx',
        ),
        migrations.AlterField(
            model_name='emssignalsource',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='energy.emssignaltype'),
        ),
    ]
