# Generated by Django 6.0.5 on 2026-07-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_home_city_home_latitude_home_longitude_and_more'),
        ('energy', '0003_emssignaltype_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emssignalsource',
            constraint=models.UniqueConstraint(fields=('home', 'device', 'signal_type'), name='unique_home_device_signal'),
        ),
    ]
